---
name: coverage

on:
  push:
    branches: [master]

jobs:
  code-coverage:
    name: code coverage
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/igaw/linux-nvme/debian.python:latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
          scripts/build.sh coverage
      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
